# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0ca89d07f1bb68f7c470ad0b528cf95222386d5be663d9984d228e60aef095f32227fb45e8adebb752a2a49238d21513022d538d1b43ee7f8c17d6ae1f5493

test:
  secret_key_base: 190b151f6a4e790d01c0c662396d88420731d10047999aff8807f49fd62745e3d76beaec2222db23267684d279394a447ca36f0a4f3ea7282b8eaa368698c659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
